import { StrictMode, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, App as AntApp, Button, Card, Col, Descriptions, Form, Input, Layout, Modal, Row, Select, Space, Statistic, Table, Tag, Timeline, Typography, message } from "antd";
import type { AlertRuleVersion, EvaluationRun, FulfillmentIncident, KnowledgeAudience, KnowledgeDocument, OpsAlert, Ticket, TicketStatus, TraceProjection } from "./types";
import { api } from "./api";
import { AgentShowcase } from "./AgentShowcase";
import "./styles.css";

const statuses: TicketStatus[] = ["open", "claimed", "waiting_customer", "approved", "rejected", "closed", "expired"];
const colors: Record<string, string> = { open: "blue", claimed: "gold", waiting_customer: "orange", approved: "green", rejected: "red", closed: "default", expired: "default", resolved: "green", muted: "default", critical: "red", warning: "orange", published: "green", retired: "default", succeeded: "green", failed: "red", running: "blue", queued: "gold" };
const stamp = (value: string | null) => value ? new Date(value).toLocaleString() : "-";

function Console() {
  const client = useQueryClient();
  const [status, setStatus] = useState<TicketStatus>(); const [selected, setSelected] = useState<Ticket>();
  const [decisionOpen, setDecisionOpen] = useState(false); const [knowledgeOpen, setKnowledgeOpen] = useState(false);
  const [resolveIncident, setResolveIncident] = useState<FulfillmentIncident>(); const [alertAction, setAlertAction] = useState<{ alert: OpsAlert; target: "resolved" | "muted" }>();
  const [traceOpen, setTraceOpen] = useState(false); const [traceInput, setTraceInput] = useState({ runId: "", caseId: "" }); const [trace, setTrace] = useState<TraceProjection>();
  const [ruleOpen, setRuleOpen] = useState(false); const [evaluationOpen, setEvaluationOpen] = useState(false); const [resultRun, setResultRun] = useState<EvaluationRun>();
  const [form] = Form.useForm(); const [knowledgeForm] = Form.useForm(); const [incidentForm] = Form.useForm(); const [alertForm] = Form.useForm(); const [ruleForm] = Form.useForm(); const [evaluationForm] = Form.useForm();
  const manager = api.actorId() === "OPS_MANAGER"; const refresh = () => client.invalidateQueries();
  const tickets = useQuery({ queryKey: ["tickets", status], queryFn: () => api.tickets(status) }); const metrics = useQuery({ queryKey: ["metrics"], queryFn: api.metrics });
  const timeline = useQuery({ queryKey: ["timeline", selected?.id], queryFn: () => api.timeline(selected!.id), enabled: Boolean(selected) }); const knowledge = useQuery({ queryKey: ["knowledge-documents"], queryFn: api.knowledgeDocuments });
  const incidents = useQuery({ queryKey: ["fulfillment-incidents"], queryFn: api.fulfillmentIncidents }); const observability = useQuery({ queryKey: ["observability-overview"], queryFn: api.observabilityOverview });
  const snapshots = useQuery({ queryKey: ["metric-snapshots"], queryFn: api.metricSnapshots }); const opsAlerts = useQuery({ queryKey: ["ops-alerts"], queryFn: api.opsAlerts }); const rules = useQuery({ queryKey: ["alert-rules"], queryFn: api.alertRules });
  const evaluationRuns = useQuery({ queryKey: ["evaluation-runs"], queryFn: api.evaluationRuns }); const evaluationResults = useQuery({ queryKey: ["evaluation-results", resultRun?.id], queryFn: () => api.evaluationResults(resultRun!.id), enabled: Boolean(resultRun) });
  const claim = useMutation({ mutationFn: api.claim, onSuccess: (ticket) => { setSelected(ticket); refresh(); message.success("已领取工单"); }, onError: (e: Error) => message.error(e.message) });
  const decide = useMutation({ mutationFn: ({ action, reasonCode, customerMessage }: { action: string; reasonCode: string; customerMessage: string }) => api.decide(selected!, action, reasonCode, customerMessage), onSuccess: (ticket) => { setSelected(ticket); setDecisionOpen(false); form.resetFields(); refresh(); message.success("审核决策已记录"); }, onError: (e: Error) => message.error(e.message) });
  const createKnowledge = useMutation({ mutationFn: api.createKnowledgeDocument, onSuccess: () => { setKnowledgeOpen(false); knowledgeForm.resetFields(); refresh(); message.success("知识草稿已创建"); }, onError: (e: Error) => message.error(e.message) });
  const queueKnowledge = useMutation({ mutationFn: api.queueKnowledgeVersion, onSuccess: () => { refresh(); message.success("索引任务已入队"); }, onError: (e: Error) => message.error(e.message) }); const publishKnowledge = useMutation({ mutationFn: api.publishKnowledgeVersion, onSuccess: () => { refresh(); message.success("知识版本已发布"); }, onError: (e: Error) => message.error(e.message) });
  const acknowledgeOpsAlert = useMutation({ mutationFn: api.acknowledgeOpsAlert, onSuccess: () => { refresh(); message.success("已领取运营告警"); }, onError: (e: Error) => message.error(e.message) });
  const actOnAlert = useMutation({ mutationFn: ({ alert, target, note }: { alert: OpsAlert; target: "resolved" | "muted"; note: string }) => target === "resolved" ? api.resolveOpsAlert(alert, note) : api.muteOpsAlert(alert, note), onSuccess: () => { setAlertAction(undefined); alertForm.resetFields(); refresh(); message.success("告警状态已更新"); }, onError: (e: Error) => message.error(e.message) });
  const acknowledgeIncident = useMutation({ mutationFn: api.acknowledgeFulfillmentIncident, onSuccess: () => { refresh(); message.success("已领取履约事故"); }, onError: (e: Error) => message.error(e.message) }); const resolveIncidentMutation = useMutation({ mutationFn: ({ incident, resolutionNote }: { incident: FulfillmentIncident; resolutionNote: string }) => api.resolveFulfillmentIncident(incident, resolutionNote), onSuccess: () => { setResolveIncident(undefined); incidentForm.resetFields(); refresh(); message.success("履约事故已解决"); }, onError: (e: Error) => message.error(e.message) });
  const publishRule = useMutation({ mutationFn: api.publishAlertRule, onSuccess: () => { setRuleOpen(false); ruleForm.resetFields(); refresh(); message.success("新告警规则版本已发布"); }, onError: (e: Error) => message.error(e.message) }); const queueEvaluation = useMutation({ mutationFn: api.queueEvaluation, onSuccess: () => { setEvaluationOpen(false); evaluationForm.resetFields(); refresh(); message.success("评测运行已入队，请由 Evaluation Worker 执行"); }, onError: (e: Error) => message.error(e.message) });
  const queryTrace = async () => { try { setTrace(await api.trace(traceInput.runId || undefined, traceInput.caseId || undefined)); } catch (e) { message.error((e as Error).message); } };
  const ticketColumns = useMemo(() => [{ title: "优先级", dataIndex: "priority", render: (v: string) => <Tag color={v === "high" ? "red" : "blue"}>{v}</Tag> }, { title: "工单", dataIndex: "id", render: (v: string) => <Typography.Text copyable={{ text: v }}>{v.slice(0, 8)}</Typography.Text> }, { title: "订单", dataIndex: "order_id" }, { title: "请求", dataIndex: "request_type" }, { title: "状态", dataIndex: "status", render: (v: string) => <Tag color={colors[v]}>{v}</Tag> }, { title: "SLA", dataIndex: "due_at", render: stamp }, { title: "负责人", dataIndex: "assigned_operator_id", render: (v: string | null) => v || "未领取" }], []);
  const alertColumns = [{ title: "等级", dataIndex: "severity", render: (v: string) => <Tag color={colors[v]}>{v}</Tag> }, { title: "状态", dataIndex: "status", render: (v: string) => <Tag color={colors[v]}>{v}</Tag> }, { title: "规则版本", dataIndex: "rule_version_id", render: (v: string) => v.slice(0, 8) }, { title: "创建时间", dataIndex: "created_at", render: stamp }, { title: "操作", render: (_: unknown, alert: OpsAlert) => <Space>{alert.status === "open" && <Button size="small" onClick={() => acknowledgeOpsAlert.mutate(alert)}>领取</Button>}{["open", "acknowledged"].includes(alert.status) && (!alert.assigned_operator_id || alert.assigned_operator_id === api.actorId()) && <><Button size="small" onClick={() => setAlertAction({ alert, target: "muted" })}>静默</Button><Button size="small" type="primary" onClick={() => setAlertAction({ alert, target: "resolved" })}>解决</Button></>}</Space> }];
  const incidentColumns = [{ title: "事故", dataIndex: "incident_type", render: (v: string) => <Tag color="red">{v}</Tag> }, { title: "售后单", dataIndex: "case_id", render: (v: number) => `#${v}` }, { title: "状态", dataIndex: "status", render: (v: string) => <Tag color={colors[v]}>{v}</Tag> }, { title: "详情", dataIndex: "detail", ellipsis: true }, { title: "操作", render: (_: unknown, incident: FulfillmentIncident) => <Space>{incident.status === "open" && <Button size="small" onClick={() => acknowledgeIncident.mutate(incident)}>领取</Button>}{incident.status !== "resolved" && (!incident.assigned_operator_id || incident.assigned_operator_id === api.actorId()) && <Button size="small" type="primary" onClick={() => setResolveIncident(incident)}>解决</Button>}</Space> }];
  const knowledgeColumns = [{ title: "标题", dataIndex: "title" }, { title: "受众", dataIndex: "audience", render: (v: string) => <Tag>{v}</Tag> }, { title: "分类", dataIndex: "category" }, { title: "当前版本", render: (_: unknown, document: KnowledgeDocument) => { const version = document.versions[0]; return version ? <Tag color={colors[version.status]}>v{version.version} · {version.status}</Tag> : "-"; } }, { title: "操作", render: (_: unknown, document: KnowledgeDocument) => { const version = document.versions[0]; if (!version) return null; if (["draft", "indexing"].includes(version.status)) return <Button size="small" onClick={() => queueKnowledge.mutate(version.id)}>{version.status === "draft" ? "建立索引" : "索引处理中"}</Button>; if (version.status === "ready") return <Button size="small" type="primary" onClick={() => publishKnowledge.mutate(version.id)}>发布</Button>; return "已生效"; } }];
  return <Layout className="shell"><Layout.Header><Typography.Title level={3}>VeriReturn · 售后运营台</Typography.Title><Select className="actor-switch" value={api.actorId()} onChange={(id) => { api.setActorId(id); window.location.reload(); }} options={[{ value: "OPS001", label: "运营人员 OPS001" }, { value: "OPS_MANAGER", label: "运营主管 OPS_MANAGER" }]} /></Layout.Header><Layout.Content>
    <Row gutter={16} className="metrics"><Col span={6}><Card><Statistic title="开放运营告警" value={observability.data?.alerts_open ?? "-"} /></Card></Col><Col span={6}><Card><Statistic title="审核工单" value={metrics.data?.tickets_total ?? "-"} /></Card></Col><Col span={6}><Card><Statistic title="待处理审核" value={metrics.data?.backlog ?? "-"} /></Card></Col><Col span={6}><Card><Statistic title="人工介入率" value={metrics.data?.manual_intervention_rate ?? 0} suffix="%" /></Card></Col></Row>
    <Card title="审核队列" extra={<Select allowClear placeholder="全部状态" value={status} onChange={setStatus} options={statuses.map((x) => ({ value: x, label: x }))} />}><Table rowKey="id" loading={tickets.isLoading} dataSource={tickets.data} columns={ticketColumns} pagination={{ pageSize: 8 }} onRow={(ticket) => ({ onClick: () => setSelected(ticket) })} /></Card>
    <Card className="knowledge-card" title="M6 · 指标趋势" extra={<Typography.Text type="secondary">按窗口倒序，保留原始快照以供复核</Typography.Text>}><Table rowKey="id" size="small" loading={snapshots.isLoading} dataSource={snapshots.data} pagination={{ pageSize: 6 }} columns={[{ title: "指标", dataIndex: "metric_name" }, { title: "数值", dataIndex: "value" }, { title: "窗口开始", dataIndex: "window_start", render: stamp }, { title: "窗口结束", dataIndex: "window_end", render: stamp }]} /></Card>
    <Card className="knowledge-card" title="M6 · 运营告警" extra={manager && <Button onClick={() => setRuleOpen(true)}>发布告警规则</Button>}><Table rowKey="id" loading={opsAlerts.isLoading} dataSource={opsAlerts.data} columns={alertColumns} pagination={{ pageSize: 5 }} /><Typography.Title level={5}>规则版本历史</Typography.Title><Table rowKey="id" size="small" loading={rules.isLoading} dataSource={rules.data} pagination={{ pageSize: 5 }} columns={[{ title: "规则", dataIndex: "rule_key" }, { title: "版本", dataIndex: "version", render: (v: number) => `v${v}` }, { title: "条件", render: (_: unknown, rule: AlertRuleVersion) => `${rule.metric_name} ${rule.comparison} ${rule.threshold}` }, { title: "等级", dataIndex: "severity", render: (v: string) => <Tag color={colors[v]}>{v}</Tag> }, { title: "状态", dataIndex: "status", render: (v: string) => <Tag color={colors[v]}>{v}</Tag> }, { title: "发布时间", dataIndex: "published_at", render: stamp }]} /></Card>
    <Card className="knowledge-card" title="M6 · 全链路 Trace" extra={<Button type="primary" onClick={() => setTraceOpen(true)}>查询并下钻</Button>}><Typography.Text type="secondary">输入 Agent run_id 或售后单 case_id，关联工具、审计、审核、知识、履约、Outbox 与事故事实。</Typography.Text></Card>
    <Card className="knowledge-card" title="M6 · 评测发布门禁" extra={manager && <Button type="primary" onClick={() => setEvaluationOpen(true)}>创建评测运行</Button>}><Table rowKey="id" loading={evaluationRuns.isLoading} dataSource={evaluationRuns.data} pagination={{ pageSize: 6 }} columns={[{ title: "评测集", dataIndex: "suite_key" }, { title: "模型", dataIndex: "model_name" }, { title: "状态", dataIndex: "status", render: (v: string) => <Tag color={colors[v]}>{v}</Tag> }, { title: "尝试", dataIndex: "attempts" }, { title: "完成时间", dataIndex: "finished_at", render: stamp }, { title: "结果", render: (_: unknown, run: EvaluationRun) => <Button size="small" onClick={() => setResultRun(run)}>查看明细</Button> }]} /></Card>
    <Card className="knowledge-card" title="M5 · 履约事故队列"><Table rowKey="id" loading={incidents.isLoading} dataSource={incidents.data} columns={incidentColumns} pagination={{ pageSize: 5 }} /></Card>
    <Card className="knowledge-card" title="M4 · 版本化知识库" extra={<Button type="primary" onClick={() => setKnowledgeOpen(true)}>新建知识草稿</Button>}><Table rowKey="id" loading={knowledge.isLoading} dataSource={knowledge.data} columns={knowledgeColumns} pagination={false} /></Card>
    <Modal open={Boolean(selected)} width={780} footer={null} onCancel={() => setSelected(undefined)} title="审核工单详情">{selected && <Space direction="vertical" size="large" className="full-width"><Descriptions bordered size="small" column={2}><Descriptions.Item label="订单">{selected.order_id}</Descriptions.Item><Descriptions.Item label="状态"><Tag color={colors[selected.status]}>{selected.status}</Tag></Descriptions.Item><Descriptions.Item label="策略">{selected.policy_version_id}</Descriptions.Item><Descriptions.Item label="触发规则">{selected.trigger_code}</Descriptions.Item><Descriptions.Item label="申请原因" span={2}>{selected.reason}</Descriptions.Item></Descriptions>{selected.status === "open" && <Button type="primary" onClick={() => claim.mutate(selected)}>领取工单</Button>}{selected.status === "claimed" && selected.assigned_operator_id === api.actorId() && <Button type="primary" onClick={() => setDecisionOpen(true)}>作出决策</Button>}<Typography.Title level={5}>审核时间线</Typography.Title><Timeline items={timeline.data?.map((event) => ({ children: <><b>{event.event_type}</b> · {event.actor_id}<br /><small>{stamp(event.created_at)} · {JSON.stringify(event.payload)}</small></> }))} /></Space>}</Modal>
    <Modal open={decisionOpen} title="提交审核决策" okText="提交" confirmLoading={decide.isPending} onCancel={() => setDecisionOpen(false)} onOk={() => form.validateFields().then((v) => decide.mutate(v))}><Form form={form} layout="vertical" initialValues={{ action: "approve_exception" }}><Form.Item name="action" label="决策" rules={[{ required: true }]}><Select options={[{ value: "approve_exception", label: "批准例外" }, { value: "reject", label: "拒绝" }, { value: "request_more_info", label: "要求补充材料" }, { value: "close_duplicate", label: "关闭重复工单" }]} /></Form.Item><Form.Item name="reasonCode" label="原因码" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="customerMessage" label="给客户的说明" rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item></Form></Modal>
    <Modal open={Boolean(resolveIncident)} title="解决履约事故" okText="提交解决记录" confirmLoading={resolveIncidentMutation.isPending} onCancel={() => setResolveIncident(undefined)} onOk={() => incidentForm.validateFields().then((v) => resolveIncident && resolveIncidentMutation.mutate({ incident: resolveIncident, resolutionNote: v.resolutionNote }))}><Form form={incidentForm} layout="vertical"><Form.Item name="resolutionNote" label="解决说明" rules={[{ required: true }, { min: 2 }]}><Input.TextArea rows={3} /></Form.Item></Form></Modal>
    <Modal open={Boolean(alertAction)} title={alertAction?.target === "resolved" ? "解决运营告警" : "静默运营告警"} okText="提交" confirmLoading={actOnAlert.isPending} onCancel={() => setAlertAction(undefined)} onOk={() => alertForm.validateFields().then((v) => alertAction && actOnAlert.mutate({ alert: alertAction.alert, target: alertAction.target, note: v.note }))}><Form form={alertForm} layout="vertical"><Form.Item name="note" label="处理说明" rules={[{ required: true }, { min: 2 }]}><Input.TextArea rows={3} /></Form.Item></Form></Modal>
    <Modal open={traceOpen} width={860} title="全链路 Trace 下钻" footer={null} onCancel={() => { setTraceOpen(false); setTrace(undefined); }}><Space direction="vertical" className="full-width"><Space><Input placeholder="Agent run_id" value={traceInput.runId} onChange={(e) => setTraceInput({ ...traceInput, runId: e.target.value })} /><Input placeholder="售后单 case_id" value={traceInput.caseId} onChange={(e) => setTraceInput({ ...traceInput, caseId: e.target.value })} /><Button type="primary" onClick={queryTrace}>查询</Button></Space>{trace && <Descriptions bordered column={1}><Descriptions.Item label="Run">{trace.run_id || "-"}</Descriptions.Item><Descriptions.Item label="售后单">{trace.case_ids.join(", ") || "-"}</Descriptions.Item>{(["tool_calls", "audit_events", "review_tickets", "knowledge_retrievals", "fulfillment_events", "outbox_events", "incidents"] as const).map((key) => <Descriptions.Item key={key} label={key}>{trace[key].length ? <Timeline items={trace[key].map((item) => ({ children: <Typography.Text code>{JSON.stringify(item)}</Typography.Text> }))} /> : "无"}</Descriptions.Item>)}</Descriptions>}</Space></Modal>
    <Modal open={ruleOpen} title="发布告警规则新版本" okText="发布" confirmLoading={publishRule.isPending} onCancel={() => setRuleOpen(false)} onOk={() => ruleForm.validateFields().then((v) => publishRule.mutate({ ...v, threshold: Number(v.threshold) }))}><Form form={ruleForm} layout="vertical" initialValues={{ comparison: ">=", severity: "warning" }}><Form.Item name="rule_key" label="稳定规则标识" rules={[{ required: true }]}><Input placeholder="agent-negative-feedback" /></Form.Item><Form.Item name="metric_name" label="指标名" rules={[{ required: true }]}><Input placeholder="agent.negative_feedback_rate" /></Form.Item><Row gutter={12}><Col span={8}><Form.Item name="comparison" label="比较符"><Select options={[{ value: ">", label: ">" }, { value: ">=", label: ">=" }]} /></Form.Item></Col><Col span={8}><Form.Item name="threshold" label="阈值" rules={[{ required: true }]}><Input type="number" min="0" step="0.0001" /></Form.Item></Col><Col span={8}><Form.Item name="severity" label="等级"><Select options={[{ value: "warning", label: "warning" }, { value: "critical", label: "critical" }]} /></Form.Item></Col></Row></Form></Modal>
    <Modal open={evaluationOpen} title="创建评测运行" okText="入队" confirmLoading={queueEvaluation.isPending} onCancel={() => setEvaluationOpen(false)} onOk={() => evaluationForm.validateFields().then((v) => queueEvaluation.mutate(v))}><Form form={evaluationForm} layout="vertical" initialValues={{ suite_key: "m5", model_name: "deepseek-v4-flash", prompt_version: "agent-prompt-v1" }}><Form.Item name="suite_key" label="评测集"><Select options={["m2", "m3", "m4", "m5"].map((x) => ({ value: x, label: x.toUpperCase() }))} /></Form.Item><Form.Item name="model_name" label="模型"><Input /></Form.Item><Form.Item name="prompt_version" label="Prompt 版本"><Input disabled /></Form.Item></Form></Modal>
    <Modal open={Boolean(resultRun)} title={`评测结果 · ${resultRun?.suite_key || ""}`} footer={null} width={800} onCancel={() => setResultRun(undefined)}><Descriptions bordered size="small" column={2}><Descriptions.Item label="状态"><Tag color={colors[resultRun?.status || ""]}>{resultRun?.status}</Tag></Descriptions.Item><Descriptions.Item label="报告">{resultRun?.report_json ? JSON.stringify(resultRun.report_json) : "尚未生成"}</Descriptions.Item></Descriptions><Table className="knowledge-card" rowKey="id" loading={evaluationResults.isLoading} dataSource={evaluationResults.data} pagination={{ pageSize: 8 }} columns={[{ title: "Case", dataIndex: "case_id" }, { title: "状态", dataIndex: "status", render: (v: string) => <Tag color={colors[v] || "default"}>{v}</Tag> }, { title: "耗时(ms)", dataIndex: "latency_ms" }, { title: "证据", dataIndex: "evidence_json", render: (v: unknown) => <Typography.Text code>{JSON.stringify(v)}</Typography.Text> }]} /></Modal>
    <Modal open={knowledgeOpen} width={760} title="新建知识草稿" okText="创建草稿" confirmLoading={createKnowledge.isPending} onCancel={() => setKnowledgeOpen(false)} onOk={() => knowledgeForm.validateFields().then((v) => createKnowledge.mutate(v))}><Form form={knowledgeForm} layout="vertical" initialValues={{ audience: "customer", category: "after-sales" }}><Form.Item name="title" label="标题" rules={[{ required: true }]}><Input /></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="stable_key" label="稳定标识" rules={[{ required: true }]}><Input placeholder="refund-policy-v2" /></Form.Item></Col><Col span={6}><Form.Item name="audience" label="受众"><Select options={(["customer", "operator", "shared"] as KnowledgeAudience[]).map((x) => ({ value: x, label: x }))} /></Form.Item></Col><Col span={6}><Form.Item name="category" label="分类"><Input /></Form.Item></Col></Row><Form.Item name="content_markdown" label="Markdown 内容" rules={[{ required: true }, { min: 10 }]}><Input.TextArea rows={10} /></Form.Item></Form></Modal>
    {[tickets, knowledge, incidents, snapshots, opsAlerts, rules, evaluationRuns].map((query, index) => query.error && <Alert key={index} className="knowledge-error" type="error" showIcon message={(query.error as Error).message} />)}
  </Layout.Content></Layout>;
}

const queryClient = new QueryClient();
const page = window.location.pathname.startsWith("/agent") ? <AgentShowcase /> : <Console />;
createRoot(document.getElementById("root")!).render(<StrictMode><QueryClientProvider client={queryClient}><AntApp>{page}</AntApp></QueryClientProvider></StrictMode>);
