"""Add M6 observability, alerts and evaluation governance.

Revision ID: 20260914_0015
Revises: 20260914_0014
Create Date: 2026-09-14 22:00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "20260914_0015"
down_revision: Union[str, Sequence[str], None] = "20260914_0014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table("agent_run_feedback", sa.Column("id", sa.String(36), primary_key=True), sa.Column("run_id", sa.String(36), nullable=False), sa.Column("actor_id", sa.String(32), nullable=False), sa.Column("rating", sa.String(16), nullable=False), sa.Column("reason_code", sa.String(64)), sa.Column("comment", sa.String(500)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("rating IN ('helpful', 'unhelpful')", name="ck_agent_run_feedback_rating"), sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"]), sa.ForeignKeyConstraint(["actor_id"], ["users.id"]), sa.UniqueConstraint("run_id", "actor_id", name="uq_agent_run_feedback_actor"))
    op.create_index("ix_agent_run_feedback_run_id", "agent_run_feedback", ["run_id"])
    op.create_index("ix_agent_run_feedback_actor_id", "agent_run_feedback", ["actor_id"])
    op.create_table("metric_computation_jobs", sa.Column("id", sa.String(36), primary_key=True), sa.Column("window_start", sa.DateTime(timezone=True), nullable=False), sa.Column("window_end", sa.DateTime(timezone=True), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="queued"), sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"), sa.Column("lease_until", sa.DateTime(timezone=True)), sa.Column("last_error", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed')", name="ck_metric_computation_job_status"), sa.UniqueConstraint("window_start", "window_end", name="uq_metric_computation_window"))
    op.create_index("ix_metric_computation_job_claim", "metric_computation_jobs", ["status", "lease_until", "created_at"])
    op.create_table("metric_snapshots", sa.Column("id", sa.String(36), primary_key=True), sa.Column("metric_name", sa.String(96), nullable=False), sa.Column("window_start", sa.DateTime(timezone=True), nullable=False), sa.Column("window_end", sa.DateTime(timezone=True), nullable=False), sa.Column("dimensions", sa.JSON(), nullable=False), sa.Column("dimension_key", sa.String(64), nullable=False, server_default="all"), sa.Column("value", sa.Numeric(18,4), nullable=False), sa.Column("computation_job_id", sa.String(36), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.ForeignKeyConstraint(["computation_job_id"], ["metric_computation_jobs.id"]), sa.UniqueConstraint("metric_name", "window_start", "window_end", "dimension_key", name="uq_metric_snapshot_window"))
    op.create_index("ix_metric_snapshots_name_window", "metric_snapshots", ["metric_name", "window_end"])
    op.create_table("alert_rule_versions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("rule_key", sa.String(64), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("metric_name", sa.String(96), nullable=False), sa.Column("comparison", sa.String(4), nullable=False), sa.Column("threshold", sa.Numeric(18,4), nullable=False), sa.Column("severity", sa.String(16), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="draft"), sa.Column("created_by", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.Column("published_at", sa.DateTime(timezone=True)), sa.CheckConstraint("status IN ('draft', 'published', 'retired')", name="ck_alert_rule_version_status"), sa.ForeignKeyConstraint(["created_by"], ["actors.id"]), sa.UniqueConstraint("rule_key", "version", name="uq_alert_rule_version"))
    op.create_index("uq_alert_rule_single_published", "alert_rule_versions", ["rule_key"], unique=True, postgresql_where=sa.text("status = 'published'"))
    op.create_table("ops_alerts", sa.Column("id", sa.String(36), primary_key=True), sa.Column("rule_version_id", sa.String(36), nullable=False), sa.Column("metric_snapshot_id", sa.String(36), nullable=False), sa.Column("fingerprint", sa.String(128), nullable=False), sa.Column("severity", sa.String(16), nullable=False), sa.Column("status", sa.String(16), nullable=False, server_default="open"), sa.Column("assigned_operator_id", sa.String(64)), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("resolution_note", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.CheckConstraint("status IN ('open', 'acknowledged', 'resolved', 'muted')", name="ck_ops_alert_status"), sa.ForeignKeyConstraint(["rule_version_id"], ["alert_rule_versions.id"]), sa.ForeignKeyConstraint(["metric_snapshot_id"], ["metric_snapshots.id"]), sa.ForeignKeyConstraint(["assigned_operator_id"], ["actors.id"]), sa.UniqueConstraint("rule_version_id", "fingerprint", name="uq_ops_alert_fingerprint"))
    op.create_index("ix_ops_alerts_queue", "ops_alerts", ["status", "severity", "created_at"])
    op.create_index("ix_ops_alerts_rule_version_id", "ops_alerts", ["rule_version_id"])
    op.create_index("ix_ops_alerts_metric_snapshot_id", "ops_alerts", ["metric_snapshot_id"])
    op.create_table("ops_alert_events", sa.Column("id", sa.String(36), primary_key=True), sa.Column("alert_id", sa.String(36), nullable=False), sa.Column("sequence_no", sa.Integer(), nullable=False), sa.Column("event_type", sa.String(64), nullable=False), sa.Column("payload", sa.JSON(), nullable=False), sa.Column("actor_id", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.ForeignKeyConstraint(["alert_id"], ["ops_alerts.id"]), sa.UniqueConstraint("alert_id", "sequence_no", name="uq_ops_alert_event_sequence"))
    op.create_index("ix_ops_alert_events_alert_id", "ops_alert_events", ["alert_id"])
    op.create_table("evaluation_suites", sa.Column("id", sa.String(36), primary_key=True), sa.Column("suite_key", sa.String(64), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("case_path", sa.String(256), nullable=False), sa.Column("checksum", sa.String(64), nullable=False), sa.Column("created_by", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.ForeignKeyConstraint(["created_by"], ["actors.id"]), sa.UniqueConstraint("suite_key", "version", name="uq_evaluation_suite_version"))
    op.create_table("evaluation_runs", sa.Column("id", sa.String(36), primary_key=True), sa.Column("suite_id", sa.String(36), nullable=False), sa.Column("requested_by", sa.String(64), nullable=False), sa.Column("model_name", sa.String(128), nullable=False), sa.Column("prompt_version", sa.String(64), nullable=False, server_default="agent-prompt-v1"), sa.Column("status", sa.String(16), nullable=False, server_default="queued"), sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"), sa.Column("lease_until", sa.DateTime(timezone=True)), sa.Column("report_json", sa.JSON()), sa.Column("last_error", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed')", name="ck_evaluation_run_status"), sa.ForeignKeyConstraint(["suite_id"], ["evaluation_suites.id"]), sa.ForeignKeyConstraint(["requested_by"], ["actors.id"]))
    op.create_index("ix_evaluation_runs_suite_id", "evaluation_runs", ["suite_id"])
    op.create_index("ix_evaluation_run_claim", "evaluation_runs", ["status", "lease_until", "created_at"])
    op.create_table("evaluation_results", sa.Column("id", sa.String(36), primary_key=True), sa.Column("evaluation_run_id", sa.String(36), nullable=False), sa.Column("case_id", sa.String(128), nullable=False), sa.Column("status", sa.String(16), nullable=False), sa.Column("latency_ms", sa.Integer(), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"]), sa.UniqueConstraint("evaluation_run_id", "case_id", name="uq_evaluation_result_case"))
    op.create_index("ix_evaluation_results_evaluation_run_id", "evaluation_results", ["evaluation_run_id"])


def downgrade() -> None:
    for table in ("evaluation_results", "evaluation_runs", "evaluation_suites", "ops_alert_events", "ops_alerts", "alert_rule_versions", "metric_snapshots", "metric_computation_jobs", "agent_run_feedback"):
        op.drop_table(table)
